quiz_list = [
    {"category": "Science & Nature",
     "type": "multiple",
     "difficulty": "medium",
     "question": "Along with Oxygen, which element is primarily responsible for the sky appearing blue?",
     "correct_answer": "Nitrogen",
     "incorrect_answers": ["Helium", "Carbon", "Hydrogen"]},
    {"category": "History",
     "type": "multiple",
     "difficulty": "hard",
     "question": "When did Spanish Peninsular War start?", "correct_answer": "1808",
     "incorrect_answers": ["1806", "1810", "1809"]},
    {"category": "Geography",
     "type": "boolean",
     "difficulty": "medium",
     "question": "Israel is 7 hours ahead of New York.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"category": "Entertainment: Cartoon & Animations",
     "type": "multiple",
     "difficulty": "easy",
     "question": "Who voices for Ruby in the animated series RWBY?",
     "correct_answer": "Lindsay Jones",
     "incorrect_answers": ["Tara Strong", "Jessica Nigri", "Hayden Panettiere"]},
    {"category": "Entertainment: Video Games",
     "type": "multiple",
     "difficulty": "easy",
     "question": "In the 2002 video game &quot;Kingdom Hearts&quot;, how many Keyblades are usable?",
     "correct_answer": "18", "incorrect_answers": ["13", "16", "15"]},
    {"category": "Animals",
     "type": "multiple",
     "difficulty": "hard",
     "question": "What scientific suborder does the family Hyaenidae belong to?",
     "correct_answer": "Feliformia",
     "incorrect_answers": ["Haplorhini", "Caniformia", "Ciconiiformes"]},
    {"category": "Science: Computers",
     "type": "multiple",
     "difficulty": "hard",
     "question": "What port does HTTP run on?", "correct_answer": "80",
     "incorrect_answers": ["53", "443", "23"]},
    {"category": "Entertainment: Board Games",
     "type": "multiple",
     "difficulty": "hard",
     "question": "What do you declare in R\u012bchi Mahjong when you&#039;ve drawn your winning tile?",
     "correct_answer": "Tsumo", "incorrect_answers": ["Ron", "R\u012bchi", "Kan"]},
    {"category": "Entertainment: Japanese Anime & Manga",
     "type": "multiple",
     "difficulty": "medium",
     "question": "What is the name of the device that allows for infinite energy in the anime &quot;Dimension W&quot;?",
     "correct_answer": "Coils", "incorrect_answers": ["Wires", "Collectors", "Tesla"]},
    {"category": "Celebrities",
     "type": "multiple",
     "difficulty": "medium",
     "question": "Which of these celebrities was not a member of the Jackson 5?",
     "correct_answer": "Bo Jackson",
     "incorrect_answers": ["Tito Jackson", "Jermaine Jackson", "Marlon Jackson"]}]
